pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/Abhishekkhankar21/cloud-admin-project.git'
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                sh 'cd terraform && terraform init'
                sh 'cd terraform && terraform apply -auto-approve'
            }
        }

        stage('Generate Inventory') {
            steps {
                sh 'cd terraform && terraform output -json > ../ansible/inventory.json'
            }
        }

        stage('Run Ansible') {
            steps {
                sh 'ansible-playbook -i ansible/inventory.json ansible/jenkins.yml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}
