---
- name: Common Server Setup
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install basic packages
      apt:
        name:
          - git
          - curl
          - python3-pip
          - docker.io
        state: present