version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Installing Terraform..."
      - curl -LO https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Terraform init..."
      - cd terraform
      - terraform init
  build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -auto-approve
      - echo "Generating inventory..."
      - cd ../scripts
      - chmod +x generate_inventory.sh
      - ./generate_inventory.sh
      - echo "Running Ansible playbooks..."
      - cd ../ansible
      - ansible-playbook -i inventory common.yml
      - ansible-playbook -i inventory app.yml
      - ansible-playbook -i inventory monitoring.yml
artifacts:
  files:
    - '**/*'